#pragma once
#include<Windows.h>

//enum Color { BULE, GREEN, RED, YELLOW };

enum Color
{
	RED = FOREGROUND_INTENSITY | FOREGROUND_RED,
	GREEN = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
	BULE = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
	YELLOW = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
	PURPLE = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
	CYAN = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,
	GRAY = FOREGROUND_INTENSITY,
	WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
	HIGHWHITE = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
	BLACK = 0,
};
